apiVersion: apps/v1
kind: Deployment
metadata:
  name: slady
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slady
  template:
    metadata:
      labels:
        app: slady
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - name: slady
        image: slady
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 10087
        readinessProbe:
          httpGet:
            path: /
            port: 10087
          initialDelaySeconds: 20
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 10087
          failureThreshold: 1
          periodSeconds: 20

        startupProbe:
          httpGet:
            path: /
            port: 10087
          failureThreshold: 30
          periodSeconds: 10
